name: Maven CI/CD for Assignment 2

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean compile --file pom.xml

      - name: Run unit tests
        run: mvn -B test --file pom.xml

      - name: Package JAR
        run: mvn -B package --file pom.xml

